name: Release

on:
  push:
    tags:
      - "v*"
      - "test-v*"
  pull_request:

permissions: write-all

env:
  UBUNTU_CODENAME: mantic
  UBUNTU_VERSION: "23.10"
  DOCKER_VERSION: "24.0.9"
  NERDCTL_VERSION: "1.7.5"
  FLANNEL_VERSION: "1.2.0"
  BINFMT_VERSION: "deploy/v7.0.0-28"
  BINFMT_QEMU_VERSION: "7.0.0"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Build for x86_64
        run: |
          make qcow OS_ARCH=x86_64 UBUNTU_CODENAME=${UBUNTU_CODENAME} UBUNTU_VERSION=${UBUNTU_VERSION} DOCKER_VERSION=${DOCKER_VERSION} BINFMT_VERSION=${BINFMT_VERSION} BINFMT_QEMU_VERSION=${BINFMT_QEMU_VERSION}
          ls -lah dist/img

      - name: Build for aarch64
        run: |
          make qcow OS_ARCH=aarch64 UBUNTU_CODENAME=${UBUNTU_CODENAME} UBUNTU_VERSION=${UBUNTU_VERSION} DOCKER_VERSION=${DOCKER_VERSION} BINFMT_VERSION=${BINFMT_VERSION} BINFMT_QEMU_VERSION=${BINFMT_QEMU_VERSION}
          ls -lah dist/img

      - name: Create release
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Note "folded" style; requires a blank line to insert actual newline
        run: >
          tag="${GITHUB_REF##*/}"

          gh release create "${tag}" --draft --title "${tag}"
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-amd64.qcow2
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-amd64.qcow2.sha512sum
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-arm64.qcow2
          dist/img/ubuntu-${UBUNTU_VERSION}-minimal-cloudimg-arm64.qcow2.sha512sum
